sudo: required
language: go

go:
  - 1.8
  - tip

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpcap0.8 libpcap0.8-dev libnuma-dev

script:
  - sudo -E env "PATH=$PATH" sh test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
